### ISSUE TITLE
fusermount processes being left behind when using auto_unmount

### ISSUE THREAD

**Issue by rydrman** [ubnt-intrepid/polyfuse#103]
I am seeing an issue where after exiting a polyfuse filesystem, the fusermount command that was created gets left behind as and never exists.

My understanding is that when the connection is dropped/closed this should exit, but I am at a loss for debugging this. 

I can also see that there is a TODO to create a more graceful shutdown, but perhaps there is an intermediary solution where the `pid` of the created process is waited on during the connection `unmount` or similar, though it feels like in my case that might just cause it to hang.

I'd appreciate any thoughts on how to debug this one

**Comment by rydrman** [comment]
It seems that this is only a problem when I add the `auto_unmount` flag to the mount options. That doesn't really make sense to me yet but when I remove that option everything works as expected and the forked fusermount command exits

**Comment by ubnt-intrepid** [comment]
The option `auto_unmount` uses inside of `fusermount` to tell that unmounting is required when the Unix socket is lost.
This option must be parsed on the polyfuse side and the socket must be closed properly when unmounted, tough the current implementation omits that process unfortunately.

I'm currently in the process of reviewing the filesystem representation and rewriting the filesystem daemon, and plan to revisit this issue after the work is finished.
